"""Write the public snapshot the marketing sites render.

Run from cron on the VPS:

    python -m app.publish

It takes a fresh copy of the journal, aggregates it, drops everything newer
than the configured lag, and writes `public-stats.json`. The static sites read
that file at build time — so the public pages never call an API, no port into
the trading data is exposed, and the published figures can be deliberately
delayed rather than live.
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import sys
import tempfile
import time
from pathlib import Path

from . import stats as stats_mod
from .config import Settings
from .store import Store, take_snapshot

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("mex.portal.publish")

#: Any key whose name suggests currency is refused before the file is written.
#: The public file is the one artefact that leaves the building, so it gets an
#: explicit gate rather than relying on the builder alone.
FORBIDDEN_KEY_PARTS = ("usd", "dollar", "money", "balance", "equity_usd", "cash", "pnl_usd")


def assert_no_currency(payload: object, path: str = "$") -> None:
    """Fail loudly if a monetary field reached the public payload."""
    if isinstance(payload, dict):
        for key, value in payload.items():
            lowered = key.lower()
            if any(part in lowered for part in FORBIDDEN_KEY_PARTS):
                raise ValueError(f"currency field {path}.{key} must not be published")
            assert_no_currency(value, f"{path}.{key}")
    elif isinstance(payload, list):
        for i, item in enumerate(payload):
            assert_no_currency(item, f"{path}[{i}]")


def build_payload(settings: Settings, lag_hours: int | None = None) -> dict:
    lag = settings.public_lag_hours if lag_hours is None else lag_hours
    cutoff = time.time() - lag * 3600

    take_snapshot(settings.journal_db, settings.snapshot_db)
    store = Store(settings.snapshot_db)

    trades = [t for t in store.trades() if (t.get("ts") or 0) <= cutoff]
    fleet = stats_mod.build(trades, store.accounts())
    store.close()

    payload = stats_mod.for_public(fleet, delay=settings.public_delay)
    payload["sample"] = False
    payload["_comment"] = (
        f"Generated by portal.app.publish. Units only; trades newer than "
        f"{lag}h are withheld. Do not edit by hand — the next run overwrites it."
    )

    assert_no_currency(payload)
    return payload


def write(payload: dict, out_path: str) -> None:
    """Atomic write, so a site build never reads a half-written file."""
    dest = Path(out_path)
    dest.parent.mkdir(parents=True, exist_ok=True)

    fd, tmp = tempfile.mkstemp(dir=dest.parent, suffix=".tmp")
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    os.replace(tmp, dest)
    log.info("wrote %s (%d markets, %d trades)", dest,
             len(payload.get("markets", [])), payload.get("headline", {}).get("trades", 0))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Publish the public stats snapshot.")
    parser.add_argument("--out", help="Output path (defaults to PORTAL_PUBLIC_OUT).")
    parser.add_argument("--lag-hours", type=int, help="Withhold trades newer than this.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the payload instead of writing it.",
    )
    args = parser.parse_args(argv)

    settings = Settings()
    try:
        payload = build_payload(settings, args.lag_hours)
    except FileNotFoundError as exc:
        log.error("%s", exc)
        return 1
    except ValueError as exc:
        log.error("refusing to publish: %s", exc)
        return 2

    if not payload["markets"]:
        log.warning("no markets in the snapshot — nothing published")
        return 3

    if args.dry_run:
        json.dump(payload, sys.stdout, indent=2, ensure_ascii=False)
        sys.stdout.write("\n")
        return 0

    write(payload, args.out or settings.public_out)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
